### ISSUE TITLE
get_ds_temporal_coverage fails with URLError if offline

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#179]
get_ds_temporal_coverage() of cate-core when called from Cate Desktop via cate-webapi fails even if local information is already available. It seems to always ask for remote info first.

RPC[6] ==> get_ds_temporal_coverage: {"jsonrpc":"2.0","id":6,"method":"get_ds_temporal_coverage","params":["esa_cci_odp","esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1"]}
Traceback (most recent call last):
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\http\client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\http\client.py", line 1152, in _send_request
    self.endheaders(body)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\http\client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\http\client.py", line 1253, in connect
    super().connect()
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 152, in send_service_method_result
    result = future.result()
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 204, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\webapi\websocket.py", line 153, in get_ds_temporal_coverage
    temporal_coverage = data_source.temporal_coverage(monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\esa_cci_odp.py", line 364, in temporal_coverage
    self.update_file_list(monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\esa_cci_odp.py", line 443, in update_file_list
    self._init_file_list(monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\esa_cci_odp.py", line 609, in _init_file_list
    cache_expiration_days=self._data_store.index_cache_expiration_days)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\esa_cci_odp.py", line 183, in _load_or_fetch_json
    json_obj = fetch_json_function(*(fetch_json_args or []), **(fetch_json_kwargs or {}))
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\esa_cci_odp.py", line 204, in _fetch_file_list_json
    monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\esa_cci_odp.py", line 123, in _fetch_solr_json
    with urllib.request.urlopen(url, timeout=timeout) as response:
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\urllib\request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Norman\Miniconda3\envs\cate-esdc\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

RPC[6] <== {"id": 6, "jsonrpc": "2.0", "error": {"message": "<urlopen error [Errno 11001] getaddrinfo failed>", "data": "Traceback (most recent call last):\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\urllib\\request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\http\\client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\http\\client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\http\\client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\http\\client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\http\\client.py\", line 877, in send\n    self.connect()\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\http\\client.py\", line 1253, in connect\n    super().connect()\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\http\\client.py\", line 849, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\socket.py\", line 694, in create_connection\n    for res in getaddrinfo(host, port, 0, SOCK_STREAM):\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\socket.py\", line 733, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno 11001] getaddrinfo failed\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\util\\web\\jsonrpchandler.py\", line 152, in send_service_method_result\n    result = future.result()\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\concurrent\\futures\\_base.py\", line 398, in result\n    return self.__get_result()\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\concurrent\\futures\\_base.py\", line 357, in __get_result\n    raise self._exception\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\concurrent\\futures\\thread.py\", line 55, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\util\\web\\jsonrpchandler.py\", line 204, in call_service_method\n    result = method(*method_params, monitor=monitor)\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\webapi\\websocket.py\", line 153, in get_ds_temporal_coverage\n    temporal_coverage = data_source.temporal_coverage(monitor=monitor)\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\ds\\esa_cci_odp.py\", line 364, in temporal_coverage\n    self.update_file_list(monitor)\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\ds\\esa_cci_odp.py\", line 443, in update_file_list\n    self._init_file_list(monitor)\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\ds\\esa_cci_odp.py\", line 609, in _init_file_list\n    cache_expiration_days=self._data_store.index_cache_expiration_days)\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\ds\\esa_cci_odp.py\", line 183, in _load_or_fetch_json\n    json_obj = fetch_json_function(*(fetch_json_args or []), **(fetch_json_kwargs or {}))\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\ds\\esa_cci_odp.py\", line 204, in _fetch_file_list_json\n    monitor=monitor)\n  File \"C:\\Users\\Norman\\IdeaProjects\\ccitools\\cate-core\\cate\\ds\\esa_cci_odp.py\", line 123, in _fetch_solr_json\n    with urllib.request.urlopen(url, timeout=timeout) as response:\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\urllib\\request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\urllib\\request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\urllib\\request.py\", line 484, in _open\n    '_open', req)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\urllib\\request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\urllib\\request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"C:\\Users\\Norman\\Miniconda3\\envs\\cate-esdc\\lib\\urllib\\request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>\n", "code": 10}}

**Comment by kbernat** [comment]
@forman I've prepared a fix, if cache exists and even if it's expired, when there a problem in fetching dataset description from server the cached data will be used. 
Is it OK for you?

**Comment by kbernat** [comment]
Do we want to process in any more elegant way the network outage issues?
