### ISSUE TITLE
cate ds list

### ISSUE THREAD

**Issue by TRSperzel** [CCI-Tools/cate-core#220]
'cate ds list' returned the following error (cate-version: 0.8.0rc1):

'cate --traceback ds list'

cate --traceback ds list
Traceback (most recent call last):
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/util/cli.py", line 274, in run_main
    args_obj.command_class().execute(args_obj)
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/util/cli.py", line 171, in execute
    return sub_command_function(command_args)
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/cli/main.py", line 1141, in _execute_list
    ds_names = sorted(data_source.name for data_source in query_data_sources())
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/core/ds.py", line 470, in query_data_sources
    results.extend(data_store.query(name))
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/ds/local.py", line 561, in query
    self._init_data_sources()
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/ds/local.py", line 589, in _init_data_sources
    data_source = self._load_data_source(os.path.join(self._store_dir, json_file))
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/ds/local.py", line 606, in _load_data_source
    return LocalDataSource.from_json_dict(json_dict, self)
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/ds/local.py", line 508, in from_json_dict
    if len(item) > 1 else (item[0], None) for item in files)
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/cate/ds/local.py", line 508, in <genexpr>
    if len(item) > 1 else (item[0], None) for item in files)
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/dateutil/parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/dateutil/parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/dateutil/parser.py", line 192, in split
    return list(cls(s))
  File "[...]/ESA_CCI_Toolbox/cate_v08/lib/python3.5/site-packages/dateutil/parser.py", line 61, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not NoneType
cate ds: error: Parser must be a string or character stream, not NoneType

Cheers,
Tim

**Comment by kbernat** [comment]
Looks like corrupted local ds json-definition. I will see how to handle it properly

**Comment by forman** [comment]
@kbernat any news?

**Comment by forman** [comment]
If not, I propose to close it or move to IRM7

**Comment by kbernat** [comment]
@forman I think we can close it for now.

**Comment by kbernat** [comment]
I'm going to review adding local ds from pattern anyway and add some error handling
