### ISSUE TITLE
cate v0.8 - error: res open

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#222]
The issue might be due to a problem on my system. Can someone reproduce the following issue?

cate --traceback res open sst esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1 1995-01-01 2010-12-31 120,-5,170,5 analysed_sst

Returns:
....start-traceback
Traceback (most recent call last):
  File "[...]/ESA_CCI_Toolbox/cate_v08_2/lib/python3.5/site-packages/cate/util/cli.py", line 274, in run_main
    args_obj.command_class().execute(args_obj)
  File "[...]/ESA_CCI_Toolbox/cate_v08_2/lib/python3.5/site-packages/cate/util/cli.py", line 171, in execute
    return sub_command_function(command_args)
  File "[...]/ESA_CCI_Toolbox/cate_v08_2/lib/python3.5/site-packages/cate/cli/main.py", line 919, in _execute_open
    mk_op_kwargs(**op_args))
  File "[...]/ESA_CCI_Toolbox/cate_v08_2/lib/python3.5/site-packages/cate/webapi/wsmanag.py", line 171, in set_workspace_resource
    data=self._post_data(op_name=op_name, op_args=json.dumps(op_args)))
  File "[...]/ESA_CCI_Toolbox/cate_v08_2/lib/python3.5/site-packages/cate/webapi/wsmanag.py", line 63, in _fetch_json
    raise error_type(message)
cate.core.workspace.WorkspaceError: positional arguments are not yet supported

Cate WebAPI service traceback

Traceback (most recent call last):
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/webapi/rest.py", line 230, in post
    # noinspection PyAbstractClass
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/core/wsmanag.py", line 300, in set_workspace_resource
    return workspace
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/core/workspace.py", line 364, in set_resource
    # noinspection PyBroadException
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/core/workspace.py", line 428, in _parse_op_args
    namespace = dict()
cate.core.workspace.WorkspaceError: positional arguments are not yet supported

cate res: error: positional arguments are not yet supported

Cate WebAPI service traceback

Traceback (most recent call last):
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/webapi/rest.py", line 230, in post
    # noinspection PyAbstractClass
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/core/wsmanag.py", line 300, in set_workspace_resource
    return workspace
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/core/workspace.py", line 364, in set_resource
    # noinspection PyBroadException
  File "[...]/ESA_CCI_Toolbox/cate/usr/lib/python3.6/site-packages/cate/core/workspace.py", line 428, in _parse_op_args
    namespace = dict()
cate.core.workspace.WorkspaceError: positional arguments are not yet supported
....end-traceback

Interestingly the lower part of the traceback reports, that it try's to access the lib-directory from the previous installation. I checked LD_LIBRARY_PATH and it did not contain the paths from the previous installed version.

**Comment by HerzogStephan** [comment]
'cate ds copy' should be used

**Comment by kbernat** [comment]
@HerzogStephan sent me his environment settings and list of running processes.
The problem was that he had some older instance of Cate running in the background.
Problem looks to be solved but perhaps we would like to inform user that there is some incompatibility between client (cli,gui) and backend?

**Comment by forman** [comment]
I agree and I will do so. However, the problem persists with development versions of core and desktop checked out from master at different points in time both still at same version no.
