### ISSUE TITLE
TimeRangeLike cannot convert

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#225]
**The following works:**
sm_remote_sources = data_store.query('esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1')
sm_remote_sources[0].make_local(local_name='sm.mon.200001_n34',time_range='2000-01-01, 2000-01-31',region='120,-5,170,5', monitor=monitor)

**The following does not:**
sm_remote_sources = data_store.query('esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1')
sm_remote_sources[0].make_local(local_name='sm.n34.july_sept2000',time_range='2000-07-01, 2000-09-31',region='120,-5,170,5', monitor=monitor)

**And returns:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cmsaf/cmsaf-ops8/sherzog/ESA_CCI_Toolbox/cate_v08_3/cate-core/lib/python3.5/site-packages/cate/ds/esa_cci_odp.py", line 808, in make_local
    self._make_local(local_ds, time_range, region, var_names, monitor)
  File "/cmsaf/cmsaf-ops8/sherzog/ESA_CCI_Toolbox/cate_v08_3/cate-core/lib/python3.5/site-packages/cate/ds/esa_cci_odp.py", line 612, in _make_local
    time_range = TimeRangeLike.convert(time_range) if time_range else None
  File "/cmsaf/cmsaf-ops8/sherzog/ESA_CCI_Toolbox/cate_v08_3/cate-core/lib/python3.5/site-packages/cate/core/types.py", line 458, in convert
    cls.assert_value_ok(False, value)
  File "/cmsaf/cmsaf-ops8/sherzog/ESA_CCI_Toolbox/cate_v08_3/cate-core/lib/python3.5/site-packages/cate/core/types.py", line 133, in assert_value_ok
    raise ValueError('cannot convert value <%s> to %s' % (text_value, cls.name()))
ValueError: cannot convert value <2000-07-01, 2000-09-31> to TimeRangeLike

**Following works just fine again:**
sm_remote_sources = data_store.query('esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1')
sm_remote_sources[0].make_local(local_name='sm.n34.july_sept2000',time_range='2000-07-01, 2000-10-01',region='120,-5,170,5', monitor=monitor)

**Comment by HerzogStephan** [comment]
Ups. September only has 30 days!

**Comment by forman** [comment]
Still, the error message could be clearer.
