### ISSUE TITLE
Can't open GHG CCI

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate-core#268]
Can't open local.esacci.GHG.satellite-orbit-frequency.L2.CO2.multi-sensor.multi-platform.VARIOUS.v2-1c.r1 in Cate Desktop.

Cate Desktop, version 0.8.0-rc.7.dev.2

arguments without labels along dimension 'sounding_dim' cannot be aligned because they have different dimension sizes: {5, 32, 54, 65, 66, 67, 75, 78, 79, 80, 81, 82, 83, 85, 89, 90, 91, 93, 97, 99, 100, 101, 102, 103, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 119, 120, 123, 124, 125, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 210, 211, 212, 213, 214, 216, 218, 219, 220, 222, 223, 224, 227, 228, 230, 233, 234, 236, 238, 239, 243, 246, 250, 251, 256, 258, 268, 272, 273, 278, 287, 293, 295}

An error (code 10) occurred while executing a backend process:

Traceback (most recent call last):
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 163, in send_service_method_result
    result = future.result()
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 216, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\webapi\websocket.py", line 293, in set_workspace_resource
    monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\wsmanag.py", line 307, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\workspace.py", line 529, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\workflow.py", line 625, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\workflow.py", line 315, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\workflow.py", line 963, in _invoke_impl
    return_value = self._op_registration(monitor=monitor, **input_values)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\op.py", line 225, in __call__
    return_value = operation(**input_values)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ops\io.py", line 62, in open_dataset
    var_names=var_names, region=region)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\ds.py", line 502, in open_dataset
    return data_source.open_dataset(time_range, region, var_names)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\local.py", line 142, in open_dataset
    ds = open_xarray_dataset(paths)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\core\ds.py", line 564, in open_xarray_dataset
    **kwargs)
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\site-packages\xarray\backends\api.py", line 524, in open_mfdataset
    combined = auto_combine(datasets, concat_dim=concat_dim, compat=compat)
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\site-packages\xarray\core\combine.py", line 396, in auto_combine
    concatenated = [_auto_concat(ds, dim=dim) for ds in grouped]
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\site-packages\xarray\core\combine.py", line 396, in <listcomp>
    concatenated = [_auto_concat(ds, dim=dim) for ds in grouped]
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\site-packages\xarray\core\combine.py", line 332, in _auto_concat
    return concat(datasets, dim=dim)
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\site-packages\xarray\core\combine.py", line 120, in concat
    return f(objs, dim, data_vars, coords, compat, positions)
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\site-packages\xarray\core\combine.py", line 210, in _dataset_concat
    datasets = align(*datasets, join='outer', copy=False, exclude=[dim])
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\site-packages\xarray\core\alignment.py", line 145, in align
    % (dim, sizes))
ValueError: arguments without labels along dimension 'sounding_dim' cannot be aligned because they have different dimension sizes: {5, 32, 54, 65, 66, 67, 75, 78, 79, 80, 81, 82, 83, 85, 89, 90, 91, 93, 97, 99, 100, 101, 102, 103, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 119, 120, 123, 124, 125, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 210, 211, 212, 213, 214, 216, 218, 219, 220, 222, 223, 224, 227, 228, 230, 233, 234, 236, 238, 239, 243, 246, 250, 251, 256, 258, 268, 272, 273, 278, 287, 293, 295}

![image](https://user-images.githubusercontent.com/206773/27591308-8f1da3a6-5b51-11e7-97cd-0bab1ab30ee1.png)

**Comment by mzuehlke** [comment]
Individual netCDF file contain sounder measurement. They do not have  a dimension "lat" or "lon" instead each measurement has a lat/lon value (point measurements).

This is not supported by cate.

Listed on Problem page: https://github.com/CCI-Tools/cate-core/wiki/Problems-with-ODP-datasets

**Comment by mzuehlke** [comment]
Can we ignore these dataset easily. GHG has only L2 data in sounder format on the ODP. No gridded data.

**Comment by mzuehlke** [comment]
The data source filter functionality fixes this issues.
See: #368
