### ISSUE TITLE
Use Case 9 happy path - Pearson_correlation fails

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-core#309]
### Expected behavior

Run script at https://github.com/CCI-Tools/cate-core/blob/master/scripts/uc09-ws.bat.
(version which was committed on 18/07/2017)
Expect it to run without errors.

### Actual behaviour

At step:
cate res set corr pearson_correlation ds_x=@ozone_sub ds_y=@cloud_sub var_x=O3_du_tot var_y=cfc

An error occurs:
cate res: error: 'geospatial_lon_min'

Note: Same error is seen when using the GUI.

### Steps to reproduce the problem

1. Open cate CLI
2. Run script above

### Specifications 

Cate 0.9.0-dev.4
Windows 7 Professional

**Comment by mzuehlke** [comment]
Traceback (most recent call last):
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/webapi/rest.py", line 116, in get
        workspace = workspace_manager.open_workspace(base_dir)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/wsmanag.py", line 190, in open_workspace
        workspace.execute_workflow(monitor=monitor.child(50))
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workspace.py", line 630, in execute_workflow
        self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workflow.py", line 629, in invoke_steps
        step.invoke(context=context, monitor=monitor.child(work=1))
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workflow.py", line 315, in invoke
        self._invoke_impl(_new_context(context, step=self), monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workflow.py", line 977, in _invoke_impl
        return_value = self._op(monitor=monitor, **input_values)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/op.py", line 211, in __call__
        return_value = self._wrapped_op(**input_values)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/ops/correlation.py", line 194, in pearson_correlation
        return adjust_spatial_attrs(retset)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/ops/normalize.py", line 190, in adjust_spatial_attrs
        lon_min = ds.attrs['geospatial_lon_min']
    KeyError: 'geospatial_lon_min'
